DROP DATABASE IF EXISTS evidenceService;
DROP USER IF EXISTS `evidence_service`@`%`;
CREATE DATABASE IF NOT EXISTS evidenceService CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `evidence_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `evidenceService`.* TO `evidence_service`@`%`;
FLUSH PRIVILEGES;

